version: "3"
services:
    app:
        build: .
        depends_on:
            - redis
            - mariadb
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        links:
          - mariadb:mariadb
    redis:
        container_name: laravel-redis
        image: redis:4-alpine
        ports:
            - 6379:6379
        volumes:
            - redis:/data
    mariadb:
        image: mariadb:10.4.4
        ports:
          - "13306:3306"
        environment:
            - MYSQL_DATABASE=forum
            - MYSQL_ROOT_PASSWORD=password

volumes:
  redis:
      driver: "local"
